global_frame: odom
robot_base_frame: wamv/base_link
publish_frequency: 5.0
update_frequency: 3.0
transform_tolerance: 0.5
obstacle_range: 50.0
raytrace_range: 40.0
footprint: [[-3,-1],[-3,1],[3,1],[3,-1]]
footprint_padding: 0.01
width: 200
height: 200
origin_x: -100
origin_y: -100
track_unknown_space: false
unknown_cost_value: 0
static_map: false
rolling_window: true
resolution: 0.05

obstacles_laser:
    observation_sources: laser
    laser: {data_type: PointCloud2, clearing: true, marking: true, topic: /wamv/sensors/lidars/lidar_wamv/points}

inflation_layer:
    inflation_radius: 0.13
    cost_scaling_factor: 20

plugins:
    - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,           type: "costmap_2d::InflationLayer"}    
