global_frame: odom
robot_base_frame: wamv/base_link
publish_frequency: 20.0
update_frequency: 100.0
transform_tolerance: 5
obstacle_range: 50.0
raytrace_range: 40.0
footprint: [[-3,-1],[-3,1],[3,1],[3,-1]]
footprint_padding: 0.61
width: 30
height: 30
origin_x: 0
origin_y: 0
track_unknown_space: false
unknown_cost_value: 0
static_map: false
rolling_window: true
resolution: 0.05

obstacles_laser:
    observation_sources: laser
    inflation_radius: 0.5
    laser: {data_type: PointCloud2, clearing: true, marking: true, topic: /wamv/sensors/lidars/lidar_wamv/points}

inflation_layer:
    inflation_radius: 4.5
    cost_scaling_factor: 2

plugins:
    - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,           type: "costmap_2d::InflationLayer"}    
